version: '3.4'

services:
  ballastlane.api:
    image: ${DOCKER_REGISTRY-}ballastlaneapi
    build:
      context: .
      dockerfile: ../src/BallastLane.Api/Dockerfile
  mongo:
    image: mongo:latest
    container_name: mongodb-container
    command: mongod --auth
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    environment:
      MONGO_INITDB_DATABASE: BallastLane
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: root

volumes:
  mongodb-data:
    driver: local  